language: node_js
node_js:
  - "10.15.0"
after_script:
  - npm run lint
  - npm run lcov-report
  - npm run coveralls-report
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
